---
- name: MacBook Pro
  hosts: macbookpro
  connection: local
  roles:
    - role: 1password
    - role: dotfiles
    - role: fish
    - role: jetbrains
    - role: mise

- name: Raspberry Pi
  hosts: raspberrypi
  become: true
  roles:
    - role: adguard-home
    - role: home-assistant
    - role: wireguard
