[Interface]
Address = 10.100.0.3/32, fd08:4711::3/128
DNS = 10.100.0.1
PrivateKey = {{ macbook_private_key }}

[Peer]
AllowedIPs = 10.100.0.1/32, fd08:4711::1/128, 192.168.50.0/24
Endpoint = {{ server_endpoint }}
PersistentKeepalive = 25
PublicKey = {{ server_public_key }}
PresharedKey = {{ macbook_pre_shared_key }}
