---
- name: Install 1Password
  community.general.homebrew_cask:
    name: 1password
    state: upgraded
- name: Install 1Password CLI
  community.general.homebrew:
    name: 1password-cli
    state: upgraded
